### PR TITLE
Student mathquill

### PR DESCRIPTION
**Pull request by zw428**
This adds a hotkey Ctrl-M to mathquill's textarea to turn math mode on and off (opposed to the dollar sign).

This also includes the branch florin-aliases.

@gcortright ready for review

### CODE REVIEW

**Comment by gcortright** [comment]
@zw428 Are the changes for student side mathquill going to be ok to include in mathquill for the editor, or are the code bases diverging from this point on?

**Comment by zw428** [comment]
@gcortright The hotkey changes only apply to mathquill textfields (the functionality that allows switching between plain text and math mode), so this will not affect the mathquill elements in ckeditor.

**Comment by zw428** [comment]
This functionality is already merged from https://github.com/educaide/hachiko/pull/991. Closing.

**Comment by zw428** [comment]
This is already being used, just wasn't merged.

**Pull request merged**
